# Generated by Django 4.1.1 on 2022-09-11 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorandnurse',
            fields=[
                ('dnid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('dFirstname', models.CharField(max_length=60)),
                ('dLastname', models.CharField(max_length=60)),
                ('dPhoneNumber', models.BigIntegerField(default=0)),
                ('dgender', models.CharField(max_length=60)),
                ('dspecialty', models.CharField(max_length=60)),
                ('dresgister', models.CharField(max_length=60)),
                ('isdoctor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('patientid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('patientfirstname', models.CharField(max_length=60)),
                ('patientlastname', models.CharField(max_length=60)),
                ('patientphonenumber', models.BigIntegerField(default=0)),
                ('patientgender', models.CharField(max_length=20)),
                ('patientaddress', models.CharField(max_length=200)),
                ('patientcity', models.CharField(max_length=200)),
                ('patientBirthday', models.CharField(max_length=50)),
                ('patientLatitude', models.CharField(max_length=200, null=True)),
                ('patientLongitude', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vitalsigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsdatetime', models.DateTimeField(default='0000-00-00')),
                ('oximetry', models.CharField(max_length=60)),
                ('respiratoryrate', models.CharField(max_length=60)),
                ('heartrate', models.CharField(max_length=60)),
                ('temperature', models.CharField(max_length=60)),
                ('bloodpressure', models.CharField(max_length=60)),
                ('bloodglucose', models.CharField(max_length=60)),
                ('vsidpatient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vitalpatientid', to='PERSONS.patients')),
            ],
        ),
        migrations.CreateModel(
            name='suggest',
            fields=[
                ('nsuggest', models.AutoField(primary_key=True, serialize=False)),
                ('datesuggest', models.DateTimeField(default='0000-00-00')),
                ('suggest', models.CharField(max_length=800)),
                ('sdoctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suggestdnid', to='PERSONS.doctorandnurse')),
                ('spatientid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suggestpatientid', to='PERSONS.patients')),
            ],
        ),
        migrations.CreateModel(
            name='helper',
            fields=[
                ('hid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('hfirstname', models.CharField(max_length=60)),
                ('hlastname', models.CharField(max_length=60)),
                ('hphoneNumber', models.BigIntegerField(default=0)),
                ('hgender', models.CharField(max_length=60)),
                ('hkinship', models.CharField(max_length=60)),
                ('hemail', models.CharField(max_length=80)),
                ('hidpatient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='helperpatientid', to='PERSONS.patients')),
            ],
        ),
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag', models.CharField(max_length=800)),
                ('diagpatientid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diagpatientid', to='PERSONS.patients')),
            ],
        ),
        migrations.CreateModel(
            name='asigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asigneddnid', to='PERSONS.doctorandnurse')),
                ('apatient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignedpatientid', to='PERSONS.patients')),
            ],
        ),
    ]
