# Generated by Django 4.1.1 on 2022-09-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERSONS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persons',
            fields=[
                ('pid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('pfirstname', models.CharField(max_length=60)),
                ('plastname', models.CharField(max_length=60)),
                ('pemail', models.CharField(max_length=90)),
                ('ppassword', models.CharField(max_length=20)),
            ],
        ),
    ]
